# -*- coding: utf-8 -*-
"""Nermin+karsli 12/1/21

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16J6Y3L2gshSATEbDTSe-VNora9q4L8qH
"""

#if condition:
   from urllib.parse import _NetlocResultMixinBase


first body
#if condition:
   second body
#else condition:
   third body


if hava yagmurluysa:
    semsiyeni al
elif hava gunesliyse:
    gunes gozlugunu al
else degilse:
    herhangi birsey alma

hava = input("Hava nasil?")
if hava == "yagmurlu":
  print("semsiye")
elif hava == "gunesli"
  print("gunes")
else:
  print("let it go")

sayi = int(input("sayi giriniz:"))

if sayi % 2 == 0:
    print("cift")
else:
    print("tek")

puan = int(input("not giriniz:"))
if puan >=90:
    print("A+")
elif puan >= 80:
    print("B+")
elif puan >= 70:
    print("C+")
elif puan >= 60:
    print("D+")
else:
    print("fail")

boy = input("boyunuz uzun mu kisa mi?")
gozluk = input("gozluklu musunuz degil misiniz?")

if boy == "uzun":
   print("boyunuz uzun")
elif boy == "kisa":
   print("kisasin")
if gozluk == "gozluk":
   print("gozluklusunuz")
else:
  print("gozluksuz")

# For While

# Dongu baslatiyor ve o donguyu bulana kadar devam ediyor.
#
#

while condition: #Truden False gecmesini bekleyecegiz.
   body

for i in "nermin":         # i icinden var mi diye bakar.
     print(i)

for i in "nermin":         # i icinden var mi diye bakar.
     print(i)
     print("Dongunun icindeyiz")

for i in "nermin":        
     print(i)
     print("Dongunun icindeyiz")
     break

for i in "nermin":         # i icinden var mi diye bakar.
     print(i)
     print("Dongunun icindeyiz")
     
while True:
     print("sonsuz dongu")
     break

for i in "omer":
   print(i)
   if i == "e":
      break

for i in "omer":
  
   if i == "e":
      break

# haricinde hepsini aliyor.
break = dongu kriliyor
#continu= istenileni almiyoruz .body birakiyoruz , digerlerini aliyoruz

# 01 2 3 4
for i in range(5):
    print(i)

for i in ["Elif", "Nermin", "Ayse"]:
   print(i)

for i in ["Elif", "Nermin", "Ayse"]:
   for j in i:
      print(j)

for i in ["Elif", "Nermin", "Ayse"]:
   for j in i:
      print(i,"->", j)




*


